# Generated by Django 6.0.6 on 2026-09-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pluggy_client_id',
            field=models.CharField(blank=True, help_text='Client ID da API Pluggy para sincronização bancária.', max_length=255, null=True, verbose_name='Pluggy Client ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pluggy_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret da API Pluggy.', max_length=255, null=True, verbose_name='Pluggy Client Secret'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pluggy_item_id',
            field=models.CharField(blank=True, help_text='Identificador do banco conectado via Pluggy Connect.', max_length=255, null=True, verbose_name='Pluggy Item ID / Conexão'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pluggy_last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização Pluggy'),
        ),
    ]
