# Generated by Django 6.0.6 on 2026-09-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_pluggy_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pluggy_item_id',
            field=models.TextField(blank=True, help_text='Item IDs / UUIDs das conexões bancárias da Pluggy (um por linha ou separados por vírgula).', null=True, verbose_name='Conexões Pluggy (Item IDs)'),
        ),
    ]
