services:
  - type: web
    name: monetra
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    releaseCommand: python manage.py migrate --noinput
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: GROQ_API_KEY
        sync: false
