# Generated by Django 6.0.6 on 2026-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotanalysis',
            name='session_id',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
