# Generated by Django 6.0.6 on 2026-06-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome da conta')),
                ('bank_name', models.CharField(max_length=100, verbose_name='nome do banco')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Poupança'), ('WALLET', 'Carteira')], default='CHECKING', max_length=20, verbose_name='tipo de conta')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'ordering': ['name'],
            },
        ),
    ]
