# Generated by Django 6.0.6 on 2026-09-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pluggy_account_id',
            field=models.CharField(blank=True, help_text='UUID da Conta na Pluggy', max_length=255, null=True, verbose_name='Account ID na Pluggy'),
        ),
        migrations.AddField(
            model_name='account',
            name='pluggy_item_id',
            field=models.CharField(blank=True, help_text='UUID do Item na Pluggy', max_length=255, null=True, verbose_name='Item ID na Pluggy'),
        ),
    ]
