# Generated by Django 6.0.6 on 2026-09-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_pluggy_account_id_account_pluggy_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL da logo do banco ou conector', max_length=500, null=True, verbose_name='URL da logo'),
        ),
    ]
