# Generated by Django 6.0.6 on 2026-06-15 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída')], max_length=10, verbose_name='tipo de transação')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('transaction_date', models.DateField(verbose_name='data da transação')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category')),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
