# Generated by Django 6.0.6 on 2026-09-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída'), ('TRANSFER', 'Transferência')], max_length=10, verbose_name='tipo de transação'),
        ),
    ]
