# Generated by Django 6.0.6 on 2026-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settlement_date',
            field=models.DateField(blank=True, help_text='Data em que a transação é efetivamente liquidada (ex: D+1, D+2).', null=True, verbose_name='data de liquidação / agendada'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída'), ('TRANSFER', 'Transferência'), ('INVESTMENT', 'Investimento')], max_length=10, verbose_name='tipo de transação'),
        ),
    ]
