# Generated by Django 6.0.6 on 2026-06-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('category_type', models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída')], max_length=10, verbose_name='tipo')),
                ('color', models.CharField(default='#667eea', max_length=7, verbose_name='cor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['category_type', 'name'],
            },
        ),
    ]
