# Generated by Django 6.0.6 on 2026-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída'), ('TRANSFER', 'Transferência'), ('INVESTMENT', 'Investimento')], max_length=10, verbose_name='tipo'),
        ),
    ]
