name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main, master ]
  # Permite disparar o deploy manualmente pela aba Actions do GitHub
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # Defina aqui o seu usuário e o nome do seu Space no Hugging Face
          HF_USERNAME: "caio007"
          HF_SPACE_NAME: "monetra"
        run: |
          # Configura o Git temporário para a Action poder criar o commit
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Garante o Git LFS
          git lfs install
          
          # Cria uma branch limpa e sem histórico chamada temp-deploy
          git checkout --orphan temp-deploy
          
          # Cria um commit único com todo o código atual
          git commit -m "Deploy to Hugging Face Spaces"
          
          # Faz o push forçado desse único commit diretamente para a branch main do Hugging Face
          git push --force https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME temp-deploy:main

